"""
Concept questions for Interview Prep: multiple choice, graded deterministically.

Each answer is a standard textbook fact (Nielsen & Chuang level), not an
opinion, so grading never needs an LLM. `answer` is the index into `choices`.
Keep explanations short: they're shown right after the user answers.
"""

QUESTIONS = [
    # ---- fundamentals ----------------------------------------------------
    {
        "id": "measure_plus",
        "topic": "Fundamentals",
        "difficulty": "warm-up",
        "question": "You measure |+⟩ = (|0⟩ + |1⟩)/√2 in the computational basis. What's the probability of getting 1?",
        "choices": ["0", "1/4", "1/2", "1/√2"],
        "answer": 2,
        "explanation": "Probability is the squared magnitude of the amplitude: |1/√2|² = 1/2. Answering 1/√2 is the classic mistake of forgetting to square.",
    },
    {
        "id": "global_phase",
        "topic": "Fundamentals",
        "difficulty": "warm-up",
        "question": "States |ψ⟩ and −|ψ⟩ differ by a global phase of −1. Which is true?",
        "choices": [
            "They give different measurement statistics in some basis",
            "They are physically indistinguishable",
            "They are orthogonal",
            "Only −|ψ⟩ is normalized",
        ],
        "answer": 1,
        "explanation": "A global phase multiplies every amplitude equally and cancels in every probability, so no measurement can tell the two apart. Relative phases between terms, by contrast, are observable.",
    },
    {
        "id": "no_cloning",
        "topic": "Fundamentals",
        "difficulty": "core",
        "question": "Why can't a CNOT copy an arbitrary unknown qubit α|0⟩ + β|1⟩ onto a |0⟩ target?",
        "choices": [
            "CNOT isn't unitary",
            "It produces α|00⟩ + β|11⟩, an entangled state, not (α|0⟩ + β|1⟩)⊗(α|0⟩ + β|1⟩)",
            "It works, but only if α and β are real",
            "The target must start in |+⟩",
        ],
        "answer": 1,
        "explanation": "CNOT copies basis states but, by linearity, maps a superposition to an entangled state. The no-cloning theorem says no unitary can copy an arbitrary unknown state.",
    },
    {
        "id": "bloch_x",
        "topic": "Fundamentals",
        "difficulty": "warm-up",
        "question": "On the Bloch sphere, what does the H gate do to |0⟩?",
        "choices": [
            "Moves it to the south pole (|1⟩)",
            "Moves it to the +X point on the equator (|+⟩)",
            "Leaves it unchanged",
            "Moves it to the +Y point on the equator (|+i⟩)",
        ],
        "answer": 1,
        "explanation": "H is a 180° rotation about the axis halfway between X and Z, which swaps the Z and X axes. |0⟩ (north pole) goes to |+⟩ (+X).",
    },
    # ---- gates -----------------------------------------------------------
    {
        "id": "pauli_anticommute",
        "topic": "Gates",
        "difficulty": "core",
        "question": "What is XZ in terms of ZX?",
        "choices": ["XZ = ZX", "XZ = −ZX", "XZ = iZX", "XZ = Y"],
        "answer": 1,
        "explanation": "Distinct Pauli matrices anticommute: XZ = −ZX. (Also XZ = −iY, so 'XZ = Y' is off by a phase.) This is the basis for commutation-based simplification rules.",
    },
    {
        "id": "t_squared",
        "topic": "Gates",
        "difficulty": "core",
        "question": "What is T²?",
        "choices": ["I", "Z", "S", "S†"],
        "answer": 2,
        "explanation": "T = diag(1, e^{iπ/4}), so T² = diag(1, e^{iπ/2}) = diag(1, i) = S. Likewise S² = Z and T⁸ = I.",
    },
    {
        "id": "clifford_universal",
        "topic": "Gates",
        "difficulty": "challenge",
        "question": "The Clifford gates (H, S, CNOT) alone are not universal. What does adding T give you?",
        "choices": [
            "Nothing new; T is already a Clifford gate",
            "An approximately universal gate set",
            "The ability to measure in the Y basis",
            "Exact synthesis of every unitary with finitely many gates",
        ],
        "answer": 1,
        "explanation": "Clifford circuits can be simulated efficiently on a classical computer (Gottesman–Knill). Adding T makes {H, S, CNOT, T} approximately universal: any unitary can be approximated to arbitrary precision, though generally not exactly.",
    },
    {
        "id": "cnot_direction",
        "topic": "Gates",
        "difficulty": "challenge",
        "question": "How do you reverse the direction of a CNOT (swap control and target)?",
        "choices": [
            "Apply X to both qubits before and after",
            "Apply H to both qubits before and after",
            "Apply S to the target before and after",
            "It can't be done without a SWAP",
        ],
        "answer": 1,
        "explanation": "(H⊗H)·CNOT(0→1)·(H⊗H) = CNOT(1→0). In the X basis the roles of control and target swap. This comes up on hardware with one-directional couplers.",
    },
    # ---- entanglement ----------------------------------------------------
    {
        "id": "bell_count",
        "topic": "Entanglement",
        "difficulty": "warm-up",
        "question": "How many Bell states are there for two qubits?",
        "choices": ["1", "2", "4", "Infinitely many"],
        "answer": 2,
        "explanation": "Four: Φ±  = (|00⟩ ± |11⟩)/√2 and Ψ± = (|01⟩ ± |10⟩)/√2. They form an orthonormal basis, which is what makes superdense coding and teleportation work.",
    },
    {
        "id": "reduced_bell",
        "topic": "Entanglement",
        "difficulty": "core",
        "question": "Two qubits are in a Bell state. What is the state of either qubit on its own?",
        "choices": ["|0⟩", "|+⟩", "The maximally mixed state I/2", "It depends on which Bell state"],
        "answer": 2,
        "explanation": "Tracing out one qubit of any Bell state leaves I/2: completely random, with no pure state of its own. That missing purity is exactly what the app's is_fully_entangled check tests for.",
    },
    {
        "id": "ghz_vs_w",
        "topic": "Entanglement",
        "difficulty": "challenge",
        "question": "You lose one qubit of a 3-qubit state. For which state do the other two stay entangled?",
        "choices": ["GHZ", "W", "Both", "Neither"],
        "answer": 1,
        "explanation": "Losing a qubit from GHZ leaves a classical mixture of |00⟩ and |11⟩ (no entanglement). W is more robust: the remaining pair is still entangled. GHZ and W are inequivalent entanglement classes.",
    },
    {
        "id": "entanglement_signal",
        "topic": "Entanglement",
        "difficulty": "core",
        "question": "Alice and Bob share a Bell pair. Can Alice send Bob a message instantly by choosing how to measure her qubit?",
        "choices": [
            "Yes, that's how quantum teleportation works",
            "Yes, but only one bit",
            "No: Bob's measurement statistics don't depend on what Alice does",
            "No, because measuring destroys entanglement before it reaches Bob",
        ],
        "answer": 2,
        "explanation": "The no-signaling theorem: Bob's reduced state is I/2 whatever Alice does, so his statistics are unchanged. Teleportation needs two classical bits from Alice, so it can't beat light speed.",
    },
    # ---- algorithms & protocols -----------------------------------------
    {
        "id": "teleport_bits",
        "topic": "Algorithms",
        "difficulty": "warm-up",
        "question": "How many classical bits must Alice send Bob to teleport one qubit?",
        "choices": ["0", "1", "2", "It depends on the state"],
        "answer": 2,
        "explanation": "Two: her Bell-measurement outcome, which tells Bob which of four Pauli corrections (I, X, Z, or XZ) to apply.",
    },
    {
        "id": "grover_speedup",
        "topic": "Algorithms",
        "difficulty": "core",
        "question": "Grover's search finds a marked item among N in about how many oracle queries?",
        "choices": ["log N", "√N", "N/2", "N"],
        "answer": 1,
        "explanation": "About (π/4)√N, a quadratic speedup over the classical N/2 average. This is provably optimal for unstructured search.",
    },
    {
        "id": "dj_queries",
        "topic": "Algorithms",
        "difficulty": "core",
        "question": "Deutsch–Jozsa decides whether f is constant or balanced with how many queries?",
        "choices": ["1", "2", "n", "2ⁿ⁻¹ + 1"],
        "answer": 0,
        "explanation": "One query, using phase kickback. A deterministic classical algorithm needs 2ⁿ⁻¹ + 1 queries in the worst case, though a randomized one succeeds with high probability in a few.",
    },
    {
        "id": "shor_part",
        "topic": "Algorithms",
        "difficulty": "challenge",
        "question": "Which part of Shor's algorithm actually needs a quantum computer?",
        "choices": [
            "Checking whether N is prime",
            "Finding the period of aˣ mod N",
            "Computing gcd(a, N)",
            "Turning the period into factors",
        ],
        "answer": 1,
        "explanation": "Period finding, via the quantum Fourier transform. Everything else (gcd, continued fractions, turning the period into factors) is efficient classically.",
    },
    # ---- hardware & noise ------------------------------------------------
    {
        "id": "t1_t2",
        "topic": "Hardware",
        "difficulty": "core",
        "question": "What does T2 measure on a physical qubit?",
        "choices": [
            "How long until |1⟩ decays to |0⟩",
            "How long the qubit keeps its phase coherence",
            "The gate time of a two-qubit gate",
            "The readout time",
        ],
        "answer": 1,
        "explanation": "T1 is energy relaxation (|1⟩ decaying to |0⟩); T2 is dephasing, the loss of the relative phase between |0⟩ and |1⟩. Physically T2 ≤ 2·T1.",
    },
    {
        "id": "depth_matters",
        "topic": "Hardware",
        "difficulty": "core",
        "question": "On today's noisy hardware, why do people care so much about circuit depth?",
        "choices": [
            "Deeper circuits use more qubits",
            "Qubits decohere over time, so longer circuits accumulate more error",
            "Depth determines the number of measurement shots",
            "Compilers can't handle depth above 100",
        ],
        "answer": 1,
        "explanation": "Depth sets roughly how long the circuit runs, and qubits decohere over time, so error grows with depth. Two-qubit gates are also the noisiest, so CNOT count matters too.",
    },
    {
        "id": "surface_code",
        "topic": "Hardware",
        "difficulty": "challenge",
        "question": "What's the main appeal of the surface code for error correction?",
        "choices": [
            "It needs only one physical qubit per logical qubit",
            "It only needs nearest-neighbor interactions on a 2D grid and has a high error threshold (~1%)",
            "It corrects errors without measuring anything",
            "It makes T gates free",
        ],
        "answer": 1,
        "explanation": "Local 2D connectivity plus a threshold around 1% match real superconducting chips. The cost is overhead: many physical qubits per logical qubit, and T gates still need magic-state distillation.",
    },
    {
        "id": "repetition_code",
        "topic": "Hardware",
        "difficulty": "core",
        "question": "The 3-qubit bit-flip code encodes α|0⟩ + β|1⟩ as α|000⟩ + β|111⟩. What can it correct?",
        "choices": [
            "Any single-qubit error",
            "A single bit flip (X error) on any one qubit",
            "A single phase flip (Z error)",
            "Two bit flips",
        ],
        "answer": 1,
        "explanation": "Majority vote catches one X error. It's blind to Z errors, which is why Shor's 9-qubit code combines bit-flip and phase-flip codes.",
    },
    # ---- advanced ----------------------------------------------------------
    {
        "id": "qpe_bits",
        "topic": "Advanced",
        "difficulty": "core",
        "question": "In phase estimation with t counting qubits, what limits the precision of the estimate?",
        "choices": [
            "The number of shots only",
            "t: the phase is read as a t-bit binary fraction",
            "The size of the eigenstate register",
            "Nothing: QPE is exact for any phase",
        ],
        "answer": 1,
        "explanation": "The register holds a t-bit fraction, so resolution is 2^−t. Phases that aren't exact t-bit fractions give a distribution peaked at the nearest value (probability at least 4/π² ≈ 0.41), and each extra bit doubles the controlled-U cost.",
    },
    {
        "id": "vqe_bound",
        "topic": "Advanced",
        "difficulty": "core",
        "question": "In noiseless VQE, why is the measured energy E(θ) always an upper bound on the ground-state energy?",
        "choices": [
            "Because the optimizer only moves downhill",
            "Because ⟨H⟩ is a weighted average of H's eigenvalues, all of which are ≥ E₀",
            "Because the ansatz is normalized to energy 0",
            "It isn't: VQE can undershoot E₀",
        ],
        "answer": 1,
        "explanation": "This is the variational principle. With noise or finite sampling an estimate can dip below E₀, which is a useful red flag when you see it in real data.",
    },
    {
        "id": "barren_plateau",
        "topic": "Advanced",
        "difficulty": "challenge",
        "question": "What is a barren plateau in variational quantum algorithms?",
        "choices": [
            "A region where the cost function is discontinuous",
            "Gradients that vanish exponentially with qubit count, making training infeasible",
            "A hardware fault that freezes qubits",
            "A local minimum the optimizer can't escape",
        ],
        "answer": 1,
        "explanation": "For many random or deep ansätze, gradient variance shrinks exponentially with system size, so you'd need exponentially many shots to see which way is downhill. Problem-inspired ansätze and shallow circuits are common mitigations.",
    },
    {
        "id": "trotter_error",
        "topic": "Advanced",
        "difficulty": "core",
        "question": "First-order Trotterization of e^{−i(A+B)t} into n steps has error that scales how?",
        "choices": ["O(t/n)", "O(t²/n), proportional to the commutator [A, B]", "O(t³/n²)", "It is exact when n ≥ 2"],
        "answer": 1,
        "explanation": "The leading error comes from [A, B] and scales as t²/n. If A and B commute it is exact. Symmetric (second-order) splitting improves it to O(t³/n²).",
    },
    {
        "id": "qaoa_layers",
        "topic": "Advanced",
        "difficulty": "core",
        "question": "In QAOA, what do the cost and mixer layers do?",
        "choices": [
            "The cost layer measures, the mixer resets",
            "The cost layer phases each bitstring by its cost; the mixer (e^{−iβΣX}) moves amplitude between bitstrings",
            "Both apply random rotations",
            "The mixer computes the cost classically",
        ],
        "answer": 1,
        "explanation": "e^{−iγC} is diagonal: it only adds cost-dependent phases. The X mixer turns those phases into amplitude changes by interference. With p → ∞ layers QAOA can approximate adiabatic evolution.",
    },
    {
        "id": "code_distance",
        "topic": "Advanced",
        "difficulty": "core",
        "question": "A quantum code has distance d = 5. How many arbitrary single-qubit errors can it always correct?",
        "choices": ["1", "2", "4", "5"],
        "answer": 1,
        "explanation": "A distance-d code corrects ⌊(d−1)/2⌋ errors, so 2 for d = 5. It can detect up to d − 1 = 4.",
    },
    {
        "id": "magic_states",
        "topic": "Advanced",
        "difficulty": "challenge",
        "question": "Why is the T gate considered expensive in a surface-code quantum computer?",
        "choices": [
            "It needs more physical qubits per logical qubit",
            "It isn't transversal, so it's implemented with distilled magic states that cost many qubits and cycles",
            "T gates have a longer physical pulse",
            "The surface code can't implement T at all",
        ],
        "answer": 1,
        "explanation": "Clifford gates are cheap in the surface code, but T requires magic-state distillation (or similar), which can dominate the space-time cost of fault-tolerant algorithms. This is why T-count is a standard cost metric.",
    },
    {
        "id": "mitigation_vs_correction",
        "topic": "Advanced",
        "difficulty": "core",
        "question": "What's the key difference between error mitigation (e.g. ZNE) and error correction?",
        "choices": [
            "None: they're two names for the same thing",
            "Mitigation post-processes noisy expectation values using extra shots; correction actively protects the state using extra qubits",
            "Mitigation needs more qubits than correction",
            "Correction only works on simulators",
        ],
        "answer": 1,
        "explanation": "Mitigation reduces bias in estimated averages at a cost in shots (sometimes exponential, as for PEC). It doesn't protect individual runs, so it can't make long algorithms like Shor's work. Correction encodes logical qubits and fixes errors during the computation.",
    },
    {
        "id": "sampler_estimator",
        "topic": "Advanced",
        "difficulty": "warm-up",
        "question": "In Qiskit, which primitive returns expectation values of observables?",
        "choices": ["Sampler", "Estimator", "Transpiler", "QuantumCircuit.measure"],
        "answer": 1,
        "explanation": "The Estimator takes (circuit, observable) pairs and returns expectation values; the Sampler returns bitstring counts from measured circuits.",
    },
    {
        "id": "routing_cost",
        "topic": "Advanced",
        "difficulty": "core",
        "question": "A transpiler inserts 4 SWAPs to route your circuit on a chip with only CX native. How many extra CNOTs is that, before optimization?",
        "choices": ["4", "8", "12", "16"],
        "answer": 2,
        "explanation": "Each SWAP decomposes into 3 CNOTs, so 12 extra two-qubit gates. Good initial layout often avoids most SWAPs entirely, which is why layout matters so much.",
    },
]

QUESTIONS_BY_ID = {q["id"]: q for q in QUESTIONS}
