"""
Concept questions for Interview Prep: multiple choice, graded deterministically.

Each answer is a standard textbook fact (Nielsen & Chuang level), not an
opinion, so grading never needs an LLM. `answer` is the index into `choices`.
Keep explanations short: they're shown right after the user answers.
"""

QUESTIONS = [
    # ---- fundamentals ----------------------------------------------------
    {
        "id": "measure_plus",
        "topic": "Fundamentals",
        "difficulty": "warm-up",
        "question": "You measure |+⟩ = (|0⟩ + |1⟩)/√2 in the computational basis. What's the probability of getting 1?",
        "choices": ["0", "1/4", "1/2", "1/√2"],
        "answer": 2,
        "explanation": "Probability is the squared magnitude of the amplitude: |1/√2|² = 1/2. Answering 1/√2 is the classic mistake of forgetting to square.",
    },
    {
        "id": "global_phase",
        "topic": "Fundamentals",
        "difficulty": "warm-up",
        "question": "States |ψ⟩ and −|ψ⟩ differ by a global phase of −1. Which is true?",
        "choices": [
            "They give different measurement statistics in some basis",
            "They are physically indistinguishable",
            "They are orthogonal",
            "Only −|ψ⟩ is normalized",
        ],
        "answer": 1,
        "explanation": "A global phase multiplies every amplitude equally and cancels in every probability, so no measurement can tell the two apart. Relative phases between terms, by contrast, are observable.",
    },
    {
        "id": "no_cloning",
        "topic": "Fundamentals",
        "difficulty": "core",
        "question": "Why can't a CNOT copy an arbitrary unknown qubit α|0⟩ + β|1⟩ onto a |0⟩ target?",
        "choices": [
            "CNOT isn't unitary",
            "It produces α|00⟩ + β|11⟩, an entangled state, not (α|0⟩ + β|1⟩)⊗(α|0⟩ + β|1⟩)",
            "It works, but only if α and β are real",
            "The target must start in |+⟩",
        ],
        "answer": 1,
        "explanation": "CNOT copies basis states but, by linearity, maps a superposition to an entangled state. The no-cloning theorem says no unitary can copy an arbitrary unknown state.",
    },
    {
        "id": "bloch_x",
        "topic": "Fundamentals",
        "difficulty": "warm-up",
        "question": "On the Bloch sphere, what does the H gate do to |0⟩?",
        "choices": [
            "Moves it to the south pole (|1⟩)",
            "Moves it to the +X point on the equator (|+⟩)",
            "Leaves it unchanged",
            "Moves it to the +Y point on the equator (|+i⟩)",
        ],
        "answer": 1,
        "explanation": "H is a 180° rotation about the axis halfway between X and Z, which swaps the Z and X axes. |0⟩ (north pole) goes to |+⟩ (+X).",
    },
    # ---- gates -----------------------------------------------------------
    {
        "id": "pauli_anticommute",
        "topic": "Gates",
        "difficulty": "core",
        "question": "What is XZ in terms of ZX?",
        "choices": ["XZ = ZX", "XZ = −ZX", "XZ = iZX", "XZ = Y"],
        "answer": 1,
        "explanation": "Distinct Pauli matrices anticommute: XZ = −ZX. (Also XZ = −iY, so 'XZ = Y' is off by a phase.) This is the basis for commutation-based simplification rules.",
    },
    {
        "id": "t_squared",
        "topic": "Gates",
        "difficulty": "core",
        "question": "What is T²?",
        "choices": ["I", "Z", "S", "S†"],
        "answer": 2,
        "explanation": "T = diag(1, e^{iπ/4}), so T² = diag(1, e^{iπ/2}) = diag(1, i) = S. Likewise S² = Z and T⁸ = I.",
    },
    {
        "id": "clifford_universal",
        "topic": "Gates",
        "difficulty": "challenge",
        "question": "The Clifford gates (H, S, CNOT) alone are not universal. What does adding T give you?",
        "choices": [
            "Nothing new; T is already a Clifford gate",
            "An approximately universal gate set",
            "The ability to measure in the Y basis",
            "Exact synthesis of every unitary with finitely many gates",
        ],
        "answer": 1,
        "explanation": "Clifford circuits can be simulated efficiently on a classical computer (Gottesman–Knill). Adding T makes {H, S, CNOT, T} approximately universal: any unitary can be approximated to arbitrary precision, though generally not exactly.",
    },
    {
        "id": "cnot_direction",
        "topic": "Gates",
        "difficulty": "challenge",
        "question": "How do you reverse the direction of a CNOT (swap control and target)?",
        "choices": [
            "Apply X to both qubits before and after",
            "Apply H to both qubits before and after",
            "Apply S to the target before and after",
            "It can't be done without a SWAP",
        ],
        "answer": 1,
        "explanation": "(H⊗H)·CNOT(0→1)·(H⊗H) = CNOT(1→0). In the X basis the roles of control and target swap. This comes up on hardware with one-directional couplers.",
    },
    # ---- entanglement ----------------------------------------------------
    {
        "id": "bell_count",
        "topic": "Entanglement",
        "difficulty": "warm-up",
        "question": "How many Bell states are there for two qubits?",
        "choices": ["1", "2", "4", "Infinitely many"],
        "answer": 2,
        "explanation": "Four: Φ±  = (|00⟩ ± |11⟩)/√2 and Ψ± = (|01⟩ ± |10⟩)/√2. They form an orthonormal basis, which is what makes superdense coding and teleportation work.",
    },
    {
        "id": "reduced_bell",
        "topic": "Entanglement",
        "difficulty": "core",
        "question": "Two qubits are in a Bell state. What is the state of either qubit on its own?",
        "choices": ["|0⟩", "|+⟩", "The maximally mixed state I/2", "It depends on which Bell state"],
        "answer": 2,
        "explanation": "Tracing out one qubit of any Bell state leaves I/2: completely random, with no pure state of its own. That missing purity is exactly what the app's is_fully_entangled check tests for.",
    },
    {
        "id": "ghz_vs_w",
        "topic": "Entanglement",
        "difficulty": "challenge",
        "question": "You lose one qubit of a 3-qubit state. For which state do the other two stay entangled?",
        "choices": ["GHZ", "W", "Both", "Neither"],
        "answer": 1,
        "explanation": "Losing a qubit from GHZ leaves a classical mixture of |00⟩ and |11⟩ (no entanglement). W is more robust: the remaining pair is still entangled. GHZ and W are inequivalent entanglement classes.",
    },
    {
        "id": "entanglement_signal",
        "topic": "Entanglement",
        "difficulty": "core",
        "question": "Alice and Bob share a Bell pair. Can Alice send Bob a message instantly by choosing how to measure her qubit?",
        "choices": [
            "Yes, that's how quantum teleportation works",
            "Yes, but only one bit",
            "No: Bob's measurement statistics don't depend on what Alice does",
            "No, because measuring destroys entanglement before it reaches Bob",
        ],
        "answer": 2,
        "explanation": "The no-signaling theorem: Bob's reduced state is I/2 whatever Alice does, so his statistics are unchanged. Teleportation needs two classical bits from Alice, so it can't beat light speed.",
    },
    # ---- algorithms & protocols -----------------------------------------
    {
        "id": "teleport_bits",
        "topic": "Algorithms",
        "difficulty": "warm-up",
        "question": "How many classical bits must Alice send Bob to teleport one qubit?",
        "choices": ["0", "1", "2", "It depends on the state"],
        "answer": 2,
        "explanation": "Two: her Bell-measurement outcome, which tells Bob which of four Pauli corrections (I, X, Z, or XZ) to apply.",
    },
    {
        "id": "grover_speedup",
        "topic": "Algorithms",
        "difficulty": "core",
        "question": "Grover's search finds a marked item among N in about how many oracle queries?",
        "choices": ["log N", "√N", "N/2", "N"],
        "answer": 1,
        "explanation": "About (π/4)√N, a quadratic speedup over the classical N/2 average. This is provably optimal for unstructured search.",
    },
    {
        "id": "dj_queries",
        "topic": "Algorithms",
        "difficulty": "core",
        "question": "Deutsch–Jozsa decides whether f is constant or balanced with how many queries?",
        "choices": ["1", "2", "n", "2ⁿ⁻¹ + 1"],
        "answer": 0,
        "explanation": "One query, using phase kickback. A deterministic classical algorithm needs 2ⁿ⁻¹ + 1 queries in the worst case, though a randomized one succeeds with high probability in a few.",
    },
    {
        "id": "shor_part",
        "topic": "Algorithms",
        "difficulty": "challenge",
        "question": "Which part of Shor's algorithm actually needs a quantum computer?",
        "choices": [
            "Checking whether N is prime",
            "Finding the period of aˣ mod N",
            "Computing gcd(a, N)",
            "Turning the period into factors",
        ],
        "answer": 1,
        "explanation": "Period finding, via the quantum Fourier transform. Everything else (gcd, continued fractions, turning the period into factors) is efficient classically.",
    },
    # ---- hardware & noise ------------------------------------------------
    {
        "id": "t1_t2",
        "topic": "Hardware",
        "difficulty": "core",
        "question": "What does T2 measure on a physical qubit?",
        "choices": [
            "How long until |1⟩ decays to |0⟩",
            "How long the qubit keeps its phase coherence",
            "The gate time of a two-qubit gate",
            "The readout time",
        ],
        "answer": 1,
        "explanation": "T1 is energy relaxation (|1⟩ decaying to |0⟩); T2 is dephasing, the loss of the relative phase between |0⟩ and |1⟩. Physically T2 ≤ 2·T1.",
    },
    {
        "id": "depth_matters",
        "topic": "Hardware",
        "difficulty": "core",
        "question": "On today's noisy hardware, why do people care so much about circuit depth?",
        "choices": [
            "Deeper circuits use more qubits",
            "Qubits decohere over time, so longer circuits accumulate more error",
            "Depth determines the number of measurement shots",
            "Compilers can't handle depth above 100",
        ],
        "answer": 1,
        "explanation": "Depth sets roughly how long the circuit runs, and qubits decohere over time, so error grows with depth. Two-qubit gates are also the noisiest, so CNOT count matters too.",
    },
    {
        "id": "surface_code",
        "topic": "Hardware",
        "difficulty": "challenge",
        "question": "What's the main appeal of the surface code for error correction?",
        "choices": [
            "It needs only one physical qubit per logical qubit",
            "It only needs nearest-neighbor interactions on a 2D grid and has a high error threshold (~1%)",
            "It corrects errors without measuring anything",
            "It makes T gates free",
        ],
        "answer": 1,
        "explanation": "Local 2D connectivity plus a threshold around 1% match real superconducting chips. The cost is overhead: many physical qubits per logical qubit, and T gates still need magic-state distillation.",
    },
    {
        "id": "repetition_code",
        "topic": "Hardware",
        "difficulty": "core",
        "question": "The 3-qubit bit-flip code encodes α|0⟩ + β|1⟩ as α|000⟩ + β|111⟩. What can it correct?",
        "choices": [
            "Any single-qubit error",
            "A single bit flip (X error) on any one qubit",
            "A single phase flip (Z error)",
            "Two bit flips",
        ],
        "answer": 1,
        "explanation": "Majority vote catches one X error. It's blind to Z errors, which is why Shor's 9-qubit code combines bit-flip and phase-flip codes.",
    },
]

QUESTIONS_BY_ID = {q["id"]: q for q in QUESTIONS}
